name: PluginManager
main: tk.rht0910.plugin_manager.PluginManager
version: 1.4
depend: [TomeitoLib]

commands:
   pman:
      description: Root command the PluginManager.
      usage: /<command> [args]
      permission: pluginmanager.help
